### ISSUE TITLE
This library may be vulnerable to a private key disclosure

### ISSUE THREAD

**Issue by axman6** [vincenthz/hs-scraps#3]
https://github.com/MystenLabs/ed25519-unsafe-libs

It looks like the likelihood of this actually being an issue is small (considering I doubt this code is used widely, Vincent correct me if I'm wrong). Given how simple the fix is (rederive the pubkey from the secret key instead of passing it in), I thought I'd make sure you knew and updated the code if necessary. It might be a good idea to also look at other implementations such as cryptonite's.

**Comment by NicolasDP** [comment]
I think he looked at cryptonite already (he wrote it).
